version: "3.9"

services:
  app:
    image: python:3.11-slim
    container_name: esp32-monitor-app
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "python main.py"
    ports:
      - "8000:8000"
    restart: unless-stopped
